### PR TITLE
feat: add get_book & search, searchID & commit info to Book, new examples

### PR DESCRIPTION
**Pull request by EmmmaTech**
I wasn't aware this repo uses conventional commit styling lmao, if you could squash merge that would be awesome :D

### CODE REVIEW

**Comment by EmmmaTech** [comment]
Almost forgot, tackles both #1 & #2.

**Comment by THEGOLDENPRO** [comment]
> I wasn't aware this repo uses conventional commit styling lmao

no worries, I don't mind

**Comment by THEGOLDENPRO** [comment]
Thanks soo much!

**Comment by THEGOLDENPRO** [comment]
closes #1 #2

**Pull request merged**
